name: example
description: A new Flutter project.

version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0" 

dependencies:
  flutter:
    sdk: flutter
  keyboard_visibility: #^0.5.6
    git: https://github.com/jamie1192/flutter_keyboard_visibility
  meta:
  timeago: ^2.0.26
  device_preview:
  images_to_pdf: ^0.0.1
  cloud_firestore: ^0.13.4
  app_review: ^1.0.0
  animations: ^1.0.0
  async: ^2.4.0
  pdf: ^1.5.0
  flutter_linkify: ^3.1.0
  flutter_mobx:
  confetti: ^0.3.0
  share: ^0.6.3+5
  camera: ^0.5.7+3
  sliding_up_panel: ^0.3.6
  eva_icons_flutter: ^2.0.0
  html: ^0.14.0+3
  file_picker: ^1.4.3+1
  open_file: ^3.0.1
  printing: ^3.1.0
  path_provider: ^1.4.2
  shared_preferences: ^0.5.4+5
  flutter_sms: ^1.1.0
  flutter_map: ^0.8.1
  latlong:
  geolocator: ^5.3.0
  mime: ^0.9.6+3
  qr_flutter: ^3.1.0
  route_pattern: ^0.5.16
  libphonenumber: ^1.0.0
  photo_view: ^0.9.0
  multi_image_picker: ^4.6.0
  diacritic: ^0.1.1
  hsluv: ^1.0.3
  flutter_staggered_grid_view: ^0.3.0
  contacts_service: ^0.3.10
  permission_handler: ^4.0.0
  firebase_auth: 0.15.4
  firebase_analytics: ^5.0.11
  firebase_messaging: ^6.0.12
  firebase_crashlytics: ^0.1.3
  cupertino_icons: ^0.1.2
  cached_network_image: ^2.0.0-rc
  device_calendar: ^1.0.0+3
  connectivity: ^0.4.8+2
  logging: ^0.11.3+2
  auto_size_text: ^2.1.0
  device_info: ^0.4.1+4
  package_info: ^0.4.0+10
  provider: ^4.0.0
  uni_links: ^0.2.0
  video_player: ^0.10.2+5
  image_picker: ^0.6.2
  flutter_svg: ^0.15.0
  url_launcher: ^5.2.5
  flutter_markdown: ^0.3.0
  image_gallery_saver: ^1.2.2
  geocoder: ^0.2.1
  flutter_portal: ^0.0.1+2
  mobx: ^0.4.0+1
  flutter_sheet_localization: ^1.0.0
  flutter_localizations:
    sdk: flutter
  fixnum:
  intl:
  rxdart: ^0.23.1
  http_extensions_cache: ^0.1.2
  http_extensions_retry: ^0.1.2
  http_extensions_log: ^0.1.2
  http_extensions_base_url: ^0.1.2
  path: ^1.6.4
  image: ^2.1.9
  hive: ^1.3.0
  jinto_api:
    path: ./dependencies/jinto_api

dependency_overrides:
  firebase_core: 0.4.4
  image_gallery_saver:
    git: https://github.com/aloisdeniel/image_gallery_saver

dev_dependencies: 
  analyzer: ^0.39.0
  build_runner: ^1.0.0
  flutter_sheet_localization_generator: ^1.2.0
  route_pattern_generator: ^0.5.17
  flutter_launcher_icons: "^0.7.2"
  hive_generator: ^0.7.0
  mobx_codegen:
  pedantic: ^1.8.0
  test:

flutter:
  uses-material-design: true
